default: &defaults
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 
  host: localhost

development:
  <<: *defaults
  database: alik_development
  
test: &test
  <<: *defaults
  database: alik_test

cucumber:
  <<: *test