default: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:
  host: localhost

development:
  <<: *defaults
  database: alik_development

test:
  <<: *defaults
  database: alik_test

production:
  <<: *defaults
  database: alik_production
