# encoding: UTF-8

User.delete_all

User.create({
  :id => 2,
  :email => "danielfeiov@gmail.com",
  :encrypted_password => "$2a$10$HCW6YM/XcKlPdJdOCrhHgOKQfmHNm1q5Fuf0gJaHUrbE750iIKTVK",
  :username => "Daniel Feio da Veiga",
  :city_id => 2465,
  :state_id => 14,
  :fields => "Cívil e Imobiliária",
  :portifolio_of_oab => "14.446",
  :phone => "(91) 8117-7947",
  :about => "Advogado militante.",
  :avatar_url => "",
  :teaching => 1,
  :professional => 5,
  :books_published => 1,
  :articles_published => 1,
  :postgraduate => false,
  :doctorate_in_law => false,
  :master_of_law => false,
  :postgraduate_in_law => false,
  :foreign_laguage => false,
  :terms_of_use => nil,
  :reset_password_token => nil,
  :reset_password_sent_at => nil,
  :remember_created_at => nil,
  :sign_in_count => 11,
  :current_sign_in_at => "Thu, 13 Sep 2012 20:08:28 BRT -03:00",
  :last_sign_in_at => "Wed, 12 Sep 2012 21:32:17 BRT -03:00",
  :current_sign_in_ip => "189.82.235.186",
  :last_sign_in_ip => "189.82.223.144",
  :created_at => "Fri, 10 Aug 2012 18:30:45 BRT -03:00",
  :updated_at => "Thu, 13 Sep 2012 20:08:28 BRT -03:00",
  :featured => true
})

User.create({
  :id => 4,
  :email => "contato.alik@gmail.com",
  :encrypted_password => "$2a$10$h1MkLOu/lSerW8lSEOhcT.oM9z835kHYRIwCQ2ghzK7Rgnm/QegMm",
  :username => "Roberto Moreira",
  :city_id => nil,
  :state_id => 19,
  :fields => "Civil e Trabalhist",
  :portifolio_of_oab => "11111",
  :phone => "(21) 6596-2335",
  :about => "Sou advogado especialista em Direito Civil e Trabalhista.",
  :avatar_url => "http://www.gravatar.com/avatar/26dbc83d8dcaec536d28737d33edaa17.png",
  :teaching => 5,
  :professional => 10,
  :books_published => 2,
  :articles_published => 3,
  :postgraduate => false,
  :doctorate_in_law => false,
  :master_of_law => false,
  :postgraduate_in_law => true,
  :foreign_laguage => true,
  :terms_of_use => nil,
  :reset_password_token => nil,
  :reset_password_sent_at => nil,
  :remember_created_at => nil,
  :sign_in_count => 14,
  :current_sign_in_at =>     "Thu, 20 Sep 2012 21:35:16 BRT -03:00",
  :last_sign_in_at =>        "Thu, 20 Sep 2012 16:14:49 BRT -03:00",
  :current_sign_in_ip =>     "189.82.141.153",                    
  :last_sign_in_ip =>        "187.42.186.180",                    
  :created_at =>             "Wed, 15 Aug 2012 11:57:50 BRT -03:00",
  :updated_at =>             "Thu, 20 Sep 2012 21:35:16 BRT -03:00",
  :featured => false

})

User.create({
  :id => 15,
  :email => "alcidesbulhoes@hotmail.com",
  :encrypted_password => "$2a$10$nE3WRik4CbAxDKWU2sOs/.b94GIxh5gxP5AzYc.XNW0MUVSOKYjmi",
  :username => "ALCIDES BULHÕES",
  :city_id => nil,
  :state_id => nil,
  :fields => "",
  :portifolio_of_oab => "",
  :phone => "",
  :about => "Advogado, especializado em Direito Público e Processual. Bacharel em Direito pela Universidade Estadual de Santa Cruz - UESC, Especializando em Direito Costitucional Aplicado pela Faculdade Damásio de Jesus, Colunista-representante do Periódico É direito; Advogado do Partido dos Trabalhadores na cidade de Valença-BA.",
  :avatar_url => "",
  :teaching => 0,
  :professional => 0,
  :books_published => 0,
  :articles_published => 0,
  :postgraduate => false,
  :doctorate_in_law => false,
  :master_of_law => false,
  :postgraduate_in_law => false,
  :foreign_laguage => false,
  :terms_of_use => nil,
  :reset_password_token => nil,
  :reset_password_sent_at => nil,
  :remember_created_at => nil,
  :sign_in_count => 1,
  :current_sign_in_at =>   "Thu, 13 Sep 2012 15:11:50 BRT -03:00",
  :last_sign_in_at =>      "Thu, 13 Sep 2012 15:11:50 BRT -03:00",
  :current_sign_in_ip =>   "201.8.70.41",                       
  :last_sign_in_ip =>      "201.8.70.41",                       
  :created_at =>           "Thu, 13 Sep 2012 15:11:50 BRT -03:00",
  :updated_at =>           "Thu, 13 Sep 2012 15:11:50 BRT -03:00",
  :featured => false

})

User.create({
  :id => 16,
  :email => "alexandrecguimaraes@me.com",
  :encrypted_password => "$2a$10$nPOALm.TUUYyo451guy53O/V33iwzQQSJA5jaBRxEaR8YBNJhp7eW",
  :username => "Alexandre Costa Cardoso Guimarães",
  :city_id => 345,
  :state_id => 5,
  :fields => "Cível / Trabalhista / Tributário",
  :portifolio_of_oab => "OAB/BA 32.884",
  :phone => "(77) 3452-1689",
  :about => "",
  :avatar_url => "",
  :teaching => 0,
  :professional => 2,
  :books_published => 0,
  :articles_published => 0,
  :postgraduate => false,
  :doctorate_in_law => false,
  :master_of_law => false,
  :postgraduate_in_law => true,
  :foreign_laguage => false,
  :terms_of_use => nil,
  :reset_password_token => nil,
  :reset_password_sent_at => nil,
  :remember_created_at => nil,
  :sign_in_count => 1,
  :current_sign_in_at =>     "Thu, 13 Sep 2012 15:30:21 BRT -03:00",
  :last_sign_in_at =>        "Thu, 13 Sep 2012 15:30:21 BRT -03:00",
  :current_sign_in_ip =>     "177.44.128.114",                    
  :last_sign_in_ip =>        "177.44.128.114",                    
  :created_at =>             "Thu, 13 Sep 2012 15:30:21 BRT -03:00",
  :updated_at =>             "Thu, 13 Sep 2012 15:32:47 BRT -03:00",
  :featured => false

})

User.create({
  :id => 17,
  :email => "rosepinheiro@terra.com.br",
  :encrypted_password => "$2a$10$SlB.V1y2s1iAYgYQ.4/jleZWMdxpzfdcxkaZYYSPfsb7wFj0yLBcG",
  :username => "Rosangela Pinheiro",
  :city_id => nil,
  :state_id => nil,
  :fields => "",
  :portifolio_of_oab => "",
  :phone => "",
  :about => "Atuo nas seguintes áreas: Trabalhista, Previdenciário, Cível e Consumidor.",
  :avatar_url => "",
  :teaching => 0,
  :professional => 0,
  :books_published => 0,
  :articles_published => 0,
  :postgraduate => false,
  :doctorate_in_law => false,
  :master_of_law => false,
  :postgraduate_in_law => false,
  :foreign_laguage => false,
  :terms_of_use => nil,
  :reset_password_token => nil,
  :reset_password_sent_at => nil,
  :remember_created_at => nil,
  :sign_in_count => 1,
  :current_sign_in_at =>   "Thu, 13 Sep 2012 16:02:27 BRT -03:00",
  :last_sign_in_at =>      "Thu, 13 Sep 2012 16:02:27 BRT -03:00",
  :current_sign_in_ip =>   "177.35.118.155",                    
  :last_sign_in_ip =>      "177.35.118.155",                    
  :created_at =>           "Thu, 13 Sep 2012 16:02:27 BRT -03:00",
  :updated_at =>           "Thu, 13 Sep 2012 16:02:27 BRT -03:00",
  :featured => false
})
        
User.create({
  :id => 14,
  :email => "lucianofrota@yahoo.com.br",
  :encrypted_password => "$2a$10$DoLbgrPcwFHCb.bJlxjG1eyTWswbmwCMBCxrTtDxrSjiZKmj/UymS",
  :username => "Luciano Leite Barbosa da Frota",
  :city_id => 678,
  :state_id => 6,
  :fields => "Empresarial e tributário, consumidor, Indenizações, Família, inventários, trabalhista, previdenciário, Imobiliário e ambiental.",
  :portifolio_of_oab => "22237",
  :phone => "(85) 8732-4696",
  :about => "Meu nome é Luciano, tenho 29 anos, sou advogado(OAB-CE 22237) no estado do Ceará  sócio-proprietário da FROTA E AGUIAR ADVOCACIA desde 2009.\r\n\r\n\r\n\r\n\r\n",
  :avatar_url => "",
  :teaching => 0,
  :professional => 4,
  :books_published => 0,
  :articles_published => 0,
  :postgraduate => false,
  :doctorate_in_law => false,
  :master_of_law => false,
  :postgraduate_in_law => true,
  :foreign_laguage => true,
  :terms_of_use => nil,
  :reset_password_token => nil,
  :reset_password_sent_at => nil,
  :remember_created_at => nil,
  :sign_in_count => 4,
  :current_sign_in_at =>     "Sat, 15 Sep 2012 16:09:32 BRT -03:00",
  :last_sign_in_at =>        "Fri, 14 Sep 2012 14:24:23 BRT -03:00",
  :current_sign_in_ip =>     "177.135.54.12",                     
  :last_sign_in_ip =>        "186.213.20.15",                     
  :created_at =>             "Thu, 13 Sep 2012 13:19:50 BRT -03:00",
  :updated_at =>             "Sat, 15 Sep 2012 16:09:32 BRT -03:00",
  :featured => false

})

User.create({
  :id => 18,
  :email => "aristotelestote_@hotmail.com",
  :encrypted_password => "$2a$10$riHwwgkqmPQnnGgP80bRd.Oq3rqEHePcLrtVaAa.47Iya8mJZBOUG",
  :username => "Aristóteles Duarte Ribeiro",
  :city_id => nil,
  :state_id => nil,
  :fields => "",
  :portifolio_of_oab => "",
  :phone => "",
  :about => "Advogado. Graduado em Direito pela Universidade Federal do Maranhão-UFMA e pós graduando em Direito Processual Civil pela Anhanguera Uniderp",
  :avatar_url => "",
  :teaching => 0,
  :professional => 0,
  :books_published => 0,
  :articles_published => 0,
  :postgraduate => false,
  :doctorate_in_law => false,
  :master_of_law => false,
  :postgraduate_in_law => false,
  :foreign_laguage => false,
  :terms_of_use => nil,
  :reset_password_token => nil,
  :reset_password_sent_at => nil,
  :remember_created_at => nil,
  :sign_in_count => 1,
  :current_sign_in_at =>     "Thu, 13 Sep 2012 16:12:17 BRT -03:00",
  :last_sign_in_at =>        "Thu, 13 Sep 2012 16:12:17 BRT -03:00",
  :current_sign_in_ip =>     "187.41.242.227",                   
  :last_sign_in_ip =>        "187.41.242.227",                   
  :created_at =>             "Thu, 13 Sep 2012 16:12:17 BRT -03:00",
  :updated_at =>             "Thu, 13 Sep 2012 16:13:11 BRT -03:00",
  :featured => false

})

User.create({
  :id => 19,
  :email => "carlos.adv@dr.com",
  :encrypted_password => "$2a$10$WDfLSjs0nyGrMxZxgFq0ium/SADtqGdwnt2b10txOeLcF0UmwgsBq",
  :username => "Carlos Roberto de Souza Júnior",
  :city_id => nil,
  :state_id => nil,
  :fields => "",
  :portifolio_of_oab => "",
  :phone => "",
  :about => "Advogado. Graduado na UNIDERP - Anhanguera, em 2010. Pós-graduando em Direito Processual Civil no Complexo Educacional Damásio de Jesus. \r\nAtuação nas searas cível, contratual e empresarial, trabalhista, imobiliária, previdenciária, tributaria e consumerista.",
  :avatar_url => "",
  :teaching => 0,
  :professional => 0,
  :books_published => 0,
  :articles_published => 0,
  :postgraduate => false,
  :doctorate_in_law => false,
  :master_of_law => false,
  :postgraduate_in_law => false,
  :foreign_laguage => false,
  :terms_of_use => nil,
  :reset_password_token => nil,
  :reset_password_sent_at => nil,
  :remember_created_at => nil,
  :sign_in_count => 1,
  :current_sign_in_at =>     "Thu, 13 Sep 2012 18:42:56 BRT -03:00",
  :last_sign_in_at =>        "Thu, 13 Sep 2012 18:42:56 BRT -03:00",
  :current_sign_in_ip =>     "177.3.235.86",                      
  :last_sign_in_ip =>        "177.3.235.86",                      
  :created_at =>             "Thu, 13 Sep 2012 18:42:56 BRT -03:00",
  :updated_at =>             "Thu, 13 Sep 2012 18:42:56 BRT -03:00",
  :featured => false

})

User.create({
  :id => 20,
  :email => "adoniasjr10@hotmail.com",
  :encrypted_password => "$2a$10$wPucD30oR/rGzcmzH9Tyv.G78Lc5CJWP4YGrkkATLxgOeOJxWzXPu",
  :username => "Adonias Júnior",
  :city_id => 270,
  :state_id => 5,
  :fields => "",
  :portifolio_of_oab => "",
  :phone => "",
  :about => "",
  :avatar_url => "",
  :teaching => 0,
  :professional => 0,
  :books_published => 0,
  :articles_published => 0,
  :postgraduate => false,
  :doctorate_in_law => false,
  :master_of_law => false,
  :postgraduate_in_law => false,
  :foreign_laguage => false,
  :terms_of_use => nil,
  :reset_password_token => nil,
  :reset_password_sent_at => nil,
  :remember_created_at => nil,
  :sign_in_count => 1,
  :current_sign_in_at =>  "Fri, 14 Sep 2012 19:29:51 BRT -03:00",
  :last_sign_in_at =>     "Fri, 14 Sep 2012 19:29:51 BRT -03:00",
  :current_sign_in_ip =>  "201.50.204.239",                    
  :last_sign_in_ip =>     "201.50.204.239",                    
  :created_at =>          "Fri, 14 Sep 2012 19:29:50 BRT -03:00",
  :updated_at =>          "Fri, 14 Sep 2012 19:54:41 BRT -03:00",
  :featured => false

})